baseURL = "https://saahilclaypool.github.io/Notes/"
languageCode = "en-us"
title = "Notes"
publishDir = "docs"
canonifyurls = true
Tagline = 'Notes on Things'

# Enable for syntax highlighting
pygmentsUseClasses = true
pygmentsCodefences = true

[markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Notes and Ramblings"
    copyright= "Copyright © 2020 Saahil Claypool"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = ""
    url = "/this_site"
    weight = -140